[project]
    name = "web"
    version = "1.0.0"
    description = "Add your description here"
    readme = "README.md"
    requires-python = ">=3.13"
    dependencies = [
        "watchdog>=6.0.0",
    ]
    license = { file = "LICENSE.txt" }
